-- Generated by nwg-displays on 2026-09-02 at 11:16:17. Do not edit manually.

hl.monitor({
    output = "DP-2",
    mode = "1920x1080@180.0",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10,
    vrr = 1
})
hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.0",
    position = "1920x0",
    scale = 1,
    bitdepth = 10,
    vrr = 0
})
